use std::io::Write;
use std::path::Path;

use anyhow::{Context, Result};
use dialoguer::{Input, Select};

const TRANSPORT_OPTIONS: &[&str] = &[
    "quic",
    "ws",
    "grpc",
    "xhttp",
    "xporta",
    "tcp",
    "prisma-tls",
    "wireguard",
];

const FORMAT_OPTIONS: &[&str] = &["TOML file", "prisma:// URI", "Print JSON"];

/// Generate a random 64-character hex secret (32 bytes).
fn generate_hex_secret() -> String {
    let mut buf = [0u8; 32];
    rand::Rng::fill(&mut rand::thread_rng(), &mut buf);
    buf.iter().map(|b| format!("{:02x}", b)).collect()
}

/// Build a client config as a structured JSON value for output flexibility.
fn build_client_config(
    server_addr: &str,
    transport: &str,
    client_id: &str,
    auth_secret: &str,
) -> serde_json::Value {
    serde_json::json!({
        "server": {
            "address": server_addr,
            "transport": transport,
        },
        "identity": {
            "client_id": client_id,
            "auth_secret": auth_secret,
        },
    })
}

/// Write a TOML config to the given output path, or stdout if `None`.
fn write_toml(config: &serde_json::Value, output: Option<&str>) -> Result<()> {
    let server = &config["server"];
    let identity = &config["identity"];

    let toml_content = format!(
        r#"# Prisma client configuration
# Generated by `prisma profile new`

[server]
address = "{}"
transport = "{}"

[identity]
client_id = "{}"
auth_secret = "{}"
"#,
        server["address"].as_str().unwrap_or_default(),
        server["transport"].as_str().unwrap_or_default(),
        identity["client_id"].as_str().unwrap_or_default(),
        identity["auth_secret"].as_str().unwrap_or_default(),
    );

    match output {
        Some(path) => {
            let p = Path::new(path);
            if let Some(parent) = p.parent() {
                if !parent.as_os_str().is_empty() && !parent.exists() {
                    std::fs::create_dir_all(parent).with_context(|| {
                        format!("Failed to create directory {}", parent.display())
                    })?;
                }
            }
            std::fs::write(p, &toml_content)
                .with_context(|| format!("Failed to write {}", path))?;
            println!("Profile written to {}", path);
        }
        None => {
            std::io::stdout().write_all(toml_content.as_bytes())?;
        }
    }
    Ok(())
}

/// Print the config as a prisma:// URI.
fn print_uri(config: &serde_json::Value) {
    let server = &config["server"];
    let identity = &config["identity"];
    // Format: prisma://client_id:auth_secret@server_addr?transport=TRANSPORT
    println!(
        "prisma://{}:{}@{}?transport={}",
        identity["client_id"].as_str().unwrap_or_default(),
        identity["auth_secret"].as_str().unwrap_or_default(),
        server["address"].as_str().unwrap_or_default(),
        server["transport"].as_str().unwrap_or_default(),
    );
}

/// Print the config as formatted JSON.
fn print_json(config: &serde_json::Value) -> Result<()> {
    println!(
        "{}",
        serde_json::to_string_pretty(config).context("Failed to serialize config as JSON")?
    );
    Ok(())
}

/// Validate a hex string has the expected length and only hex characters.
fn validate_hex_secret(input: &str) -> bool {
    input.len() == 64 && input.chars().all(|c| c.is_ascii_hexdigit())
}

/// Run the interactive profile creation wizard.
pub fn run_wizard(output: Option<String>) -> Result<()> {
    println!("Prisma Profile Wizard");
    println!("=====================");
    println!();

    // Step 1: Server address
    let server_addr: String = Input::new()
        .with_prompt("Server address (host:port)")
        .interact_text()
        .context("Failed to read server address")?;

    // Step 2: Transport
    let transport_idx = Select::new()
        .with_prompt("Transport")
        .items(TRANSPORT_OPTIONS)
        .default(0)
        .interact()
        .context("Failed to read transport selection")?;
    let transport = TRANSPORT_OPTIONS[transport_idx];

    // Step 3: Client ID
    let default_uuid = uuid::Uuid::new_v4().to_string();
    let client_id: String = Input::new()
        .with_prompt("Client ID (UUID)")
        .default(default_uuid)
        .interact_text()
        .context("Failed to read client ID")?;

    // Step 4: Auth secret
    let default_secret = generate_hex_secret();
    let auth_secret: String = Input::new()
        .with_prompt("Auth secret (64 hex chars)")
        .default(default_secret)
        .validate_with(|input: &String| -> std::result::Result<(), String> {
            if validate_hex_secret(input) {
                Ok(())
            } else {
                Err("Auth secret must be exactly 64 hex characters".to_string())
            }
        })
        .interact_text()
        .context("Failed to read auth secret")?;

    // Step 5: Output format
    let format_idx = Select::new()
        .with_prompt("Output format")
        .items(FORMAT_OPTIONS)
        .default(0)
        .interact()
        .context("Failed to read output format")?;

    // Build config and output
    let config = build_client_config(&server_addr, transport, &client_id, &auth_secret);
    match format_idx {
        0 => write_toml(&config, output.as_deref())?,
        1 => print_uri(&config),
        2 => print_json(&config)?,
        _ => unreachable!(),
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_hex_secret() {
        let secret = generate_hex_secret();
        assert_eq!(secret.len(), 64);
        assert!(secret.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn test_validate_hex_secret() {
        assert!(validate_hex_secret(
            "aabbccdd00112233445566778899aabbccddeeff0011223344556677aabbccdd"
        ));
        assert!(!validate_hex_secret("short"));
        assert!(!validate_hex_secret(
            "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"
        ));
    }

    #[test]
    fn test_build_client_config() {
        let config = build_client_config("1.2.3.4:8443", "quic", "test-uuid", "aabb");
        assert_eq!(config["server"]["address"], "1.2.3.4:8443");
        assert_eq!(config["server"]["transport"], "quic");
        assert_eq!(config["identity"]["client_id"], "test-uuid");
        assert_eq!(config["identity"]["auth_secret"], "aabb");
    }
}
